
import { GoogleGenAI } from "@google/genai";

export default async function handler(req, res) {
  // CORS Headers
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  let body = req.body;
  if (typeof body === 'string') {
    try {
      body = JSON.parse(body);
    } catch (e) {
      console.error("Failed to parse request body:", e);
      return res.status(400).json({ error: 'Invalid JSON body' });
    }
  }

  const { rawInput } = body || {};

  if (!rawInput) {
    return res.status(400).json({ error: 'Missing rawInput in request body' });
  }

  // Check multiple possible environment variable names
  const apiKey = process.env.VITE_GEMINI_API_KEY || process.env.API_KEY || process.env.GOOGLE_API_KEY || process.env.GEMINI_API_KEY;

  // Debug log (will show in Vercel logs) to help verify which keys are seen
  console.log("Checking environment variables for API Key...");
  console.log("VITE_GEMINI_API_KEY exists?", !!process.env.VITE_GEMINI_API_KEY);
  console.log("API_KEY exists?", !!process.env.API_KEY);

  if (!apiKey) {
    console.error("CRITICAL: No valid API Key found in environment variables.");
    return res.status(500).json({ 
        error: 'Server configuration error: API Key missing',
        details: 'Checked: VITE_GEMINI_API_KEY, API_KEY, GOOGLE_API_KEY'
    });
  }

  try {
    const ai = new GoogleGenAI({ apiKey: apiKey });
    const today = new Date().toISOString().split('T')[0];
    const prompt = `
      Current Date: ${today}
      Analyze this barter offer request: "${rawInput}"
      
      Return a JSON object with:
      - title (Hebrew, professional)
      - description (Hebrew, persuasive)
      - offeredService (Short Hebrew)
      - requestedService (Short Hebrew)
      - location (Hebrew, City or 'Remote')
      - tags (Array of strings)
      - expirationDate (YYYY-MM-DD, only if a deadline is explicitly mentioned relative to today)
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        responseMimeType: "application/json"
      }
    });

    const text = response.text;
    if (text) {
      let jsonResponse;
      try {
        jsonResponse = JSON.parse(text);
      } catch (parseError) {
        console.error("Failed to parse Gemini response as JSON:", text);
        return res.status(500).json({ error: 'AI returned invalid JSON' });
      }
      return res.status(200).json(jsonResponse);
    } else {
      console.error("Gemini returned empty text.");
      return res.status(500).json({ error: 'No content generated by AI' });
    }

  } catch (error: any) {
    console.error("Gemini API execution failed:", error);
    return res.status(500).json({ error: 'Failed to optimize offer', details: error.message });
  }
}
